# Generated by Django 3.2.16 on 2023-05-30 14:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0002_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cermon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('theme', models.CharField(max_length=150)),
                ('reading', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('date', models.CharField(default='YYYY-MM-DD', max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
