# Generated by Django 3.2.16 on 2023-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0005_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
