# Generated by Django 3.2.16 on 2023-05-31 06:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0008_alter_paymentmethod_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('ministry', 'ministry'), ('outreach', 'outreach'), ('donation', 'donation')], max_length=255)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
